# A list of modules and whether they are enabled
modules:
  bonemeal-flowers: false
  composter-output: true
  composter-spreader: false
  decoarsify: true
  dynamic-trample: true
  fancy-trees: false
  fast-leaf-decay: false
  grass-drops: true
  growth-dance: false
  interactive-harvest: true
  lumberjack: false
  rejuvenated-bushes: false
  sapling-replant: false
  sniffer-drops: false