# GardeningTweaks Plugin config.yml
# For ease of use this config has been sorted in Alphabetical Order

# Minecraft names their Trees weirdly so here is a list of the tree types:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/TreeType.html

# bonemeal-flowers: Grow *some* small flowers into taller versions by bonemealing them
bonemeal-flowers:
  # enabled: Whether Bonemeal Flowers is enabled
  enabled: true

# custom-grass-drops: Changes the drops of grass (Leave empty for Default)
custom-grass-drops:
  # enabled: Whether Custom Grass Drops is enabled
  enabled: true
  # items: A list of items that will have a chance of being dropped by grass
  items:
    - "WHEAT_SEEDS"
    - "BEETROOT_SEEDS"
    - "PUMPKIN_SEEDS"
    - "MELON_SEEDS"

# decoarsify: Coarse Dirt drops normal dirt
decoarsify:
  # enabled: Whether Decoarsify is enabled
  enabled: false

# dynamic-trample: Adds trample options for your farmland for when jumped on by a player
dynamic-trample:
  # enabled: Whether Dynamic Trample is enabled
  enabled: true
  # feather-falling: Whether Feather Falling stops users from trampling farmland
  feather-falling: true
  # creative-mode: Whether Creative Mode stops users from trampling farmland
  creative-mode: true

# fast-leaf-decay: Leaves disappear as soon as the last log has been broken
fast-leaf-decay:
  # enabled: Whether Fast Leaf Decay is enabled
  enabled: true
  # sounds: Whether a sound will be made when leaves decay
  sounds: false
  # particles: Whether particles will appear when leaves decay
  particles: false

# growth-dance: Crouch near your crops to help give them a growth boost!
growth-dance:
  # mode: (DEFAULT: Grows on crouch, DISABLED: Disables Growth Dance)
  mode: true
  # growth-rate: The amount of times a crop can have a chance of receiving a boost per second (maximum of 20)
  growth-rate: 2
  # blocks: A list of blocks that will be effected by Growth Dance
  blocks:
    - "BEETROOTS"
    - "CACTUS"
    - "CARROTS"
    - "CHORUS_FLOWER"
    - "KELP"
    - "MELON_STEM"
    - "NETHER_WART"
    - "POTATOES"
    - "PUMPKIN_STEM"
    - "SUGAR_CANE"
    - "SWEET_BERRY_BUSH"
    - "TWISTING_VINES"
    - "WEEPING_VINES"
    - "WHEAT"

# interactive-harvest: Right Click fully grown crops to harvest
interactive-harvest:
  # enabled: Whether Interactive Harvest is enabled
  enabled: true
  # blocks: A list of blocks that will be effected by Interactive Harvest
  blocks:
    - "BEETROOTS"
    - "CARROTS"
    - "NETHER_WART"
    - "POTATOES"
    - "SWEET_BERRY_BUSH"
    - "WHEAT"

# lumberjack: Break the entirety of a tree at once (All connected logs)
lumberjack:
  # mode: (DEFAULT: Breaks connected logs, DISABLED: Disables Lumberjack)
  mode: DEFAULT
  # blocks: A list of blocks that will be effected by Lumberjack
  blocks:
    - "OAK_LOG"
    - "SPRUCE_LOG"
    - "BIRCH_LOG"
    - "JUNGLE_LOG"
    - "ACACIA_LOG"
    - "DARK_OAK_LOG"
    - "MANGROVE_LOG"
    - "CRIMSON_STEM"
    - "WARPED_STEM"

# rejuvenated-bushes: Dead bushes can be changed into saplings by right-clicking with different seeds
rejuvenated-bushes:
  # enabled: Whether Rejuvenated Bushes is enabled
  enabled: true

# trees: General Configuration for different Tree Types
trees:
  # DEFAULT: The tree type that is effected (DEFAULT will affect all trees not defined)
  DEFAULT:
    # spread-blocks: Whether this tree type will change surrounding dirt/coarse dirt to grass blocks when grown
    spread-blocks:
      - "GRASS_BLOCK"
    # spread-blocks-on: The blocks that will be replaced by 'spread-blocks' (Leave empty to replace all full blocks)
    spread-blocks-on:
      - "DIRT"
      - "COARSE_DIRT"
    # flowers: The flowers/blocks that will grow around trees on grass blocks if 'growFlowers' is set to 'true'
    flowers:
      # GRASS: The flower/block type that has a chance to spawn
      # The number following is the weight of the particular block being set
      GRASS: 75
      POPPY: 12.5
      DANDELION: 12.5
  TREE: # 'TREE' is 'OAK'
    spread-blocks:
      - "GRASS_BLOCK"
    spread-blocks-on:
      - "DIRT"
      - "COARSE_DIRT"
    flowers:
      POPPY: 1
      ALLIUM: 1
  CRIMSON_FUNGUS:
    spread-blocks:
      - "CRIMSON_NYLIUM"
    spread-blocks-on:
      - "NETHERRACK"
      - "WARPED_NYLIUM"
    flowers:
      CRIMSON_ROOTS: 1
  WARPED_FUNGUS:
    spread-blocks:
      - "WARPED_NYLIUM"
    spread-blocks-on:
      - "NETHERRACK"
      - "CRIMSON_NYLIUM"
    flowers:
        WARPED_ROOTS: 1
