name: GardeningTweaks
version: '${project.version}'
main: me.dave.gardeningtweaks.GardeningTweaks
api-version: 1.16
authors: [ OakLoaf ]
description: Spruces up your gardening
softdepend:
  - CoreProtect
  - packetevents
  - ProtocolLib
  - RealisticBiomes
  - GriefPrevention
  - HuskClaims
  - HuskTowns
  - Lands
commands:
  gardeningtweaks:
    description: The main GardeningTweaks Command.
    aliases: gt
    usage: /gardeningtweaks