name: GardeningTweaks
version: '${project.version}'
main: me.dave.gardeningtweaks.GardeningTweaks
api-version: 1.16
authors: [ Dav_e_ ]
description: Spruces up your gardening
softdepend:
  - CoreProtect
  - ProtocolLib
  - RealisticBiomes
  - GriefPrevention
  - HuskClaims
commands:
  gardeningtweaks:
    description: The main GardeningTweaks Command.
    aliases: gt
    usage: /gardeningtweaks